server: 
  port: 8081
  servlet:
    context-path: /fesco-test-server
logging:
  level:
    org.springframework: INFO
spring:
  application:
    name: fesco-test
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;TrustServerCertificate=True;databaseName=test
    username: root
    password: 123456
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect


